version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(GHA)"
    labels:
      - "dependencies"
      - "patch"
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(TF)"
    labels:
      - "dependencies"
      - "patch"
  - package-ecosystem: "terraform"
    directory: "/modules/*"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(TF)"
    labels:
      - "dependencies"
      - "patch"
  - package-ecosystem: "gomod"
    directory: "/tests"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(Go)"
    labels:
      - "dependencies"
      - "patch"
